apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: pd-graphiti
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: fast-ssd  # Uncomment and specify your storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: pd-graphiti
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: fast-ssd  # Uncomment and specify your storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-backups-pvc
  namespace: pd-graphiti
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: standard  # Can use slower storage for backups